# Generated by Django 3.2.21 on 2023-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=45)),
                ('end_time', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'slots',
                'managed': False,
            },
        ),
    ]
