# Generated by Django 3.2.21 on 2023-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('turfname', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'turf',
                'managed': False,
            },
        ),
    ]
