# Generated by Django 3.2.21 on 2023-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=45)),
                ('house_name', models.CharField(max_length=45)),
                ('post', models.CharField(max_length=45)),
                ('pin', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('phn_no', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
