# Generated by Django 3.2.21 on 2023-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('company_name', models.CharField(max_length=45)),
                ('liscence_no', models.CharField(max_length=45)),
                ('proof', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
    ]
